name: flutter_example
description: Unified iOS Flutter examples for xcross.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.13.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  flutter_quill: ^11.5.1
  drift: ^2.31.0
  drift_flutter: 0.3.1
  path_provider: ^2.1.6
  shared_preferences: ^2.5.5
  web: ^1.1.1
  cupertino_icons: ^1.0.9
  get_it: ^9.2.1
  file_picker: ^12.0.0
  path: ^1.9.1
  url_launcher: ^6.3.2
  http: ^1.6.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.8
  uuid: ^4.5.3
  flutter_local_notifications: ^22.0.1
  timezone: ^0.11.1
  flutter_timezone: ^5.1.0
  firebase_core: ^4.13.0
  firebase_auth: ^6.5.7
  cloud_firestore: ^6.1.0
  firebase_storage: ^13.4.6
  google_sign_in: ^7.2.0
  firebase_messaging: ^16.4.2
  amplify_flutter: ^2.15.0
  amplify_auth_cognito: ^2.15.0
  amplify_api: ^2.15.0
  amplify_storage_s3: ^2.15.0
  web_socket_channel: ^3.0.3
  flutter_svg: ^2.3.0
  device_info_plus: ^13.2.0
  dio: ^5.9.2
  flutter_vector_icons: ^2.0.0
  flutter_rust_bridge: 2.13.0-beta.6
  flutter_rust_bridge_hooks: 2.13.0-beta.6

dev_dependencies:
  drift_dev: ^2.31.0
  build_runner: ^2.13.1
  flutter_launcher_icons: ^0.14.4
  mocktail: ^1.0.5
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  bloc_test: ^10.0.0
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf
